export default [
    {
        "id":1,
        "path":"/button/split",
        "name":"split"
    },
    {
        "id":2,
        "path":"/button/alert",
        "name":"alert"
    },
    {
        "id":3,
        "path":"/button/outline",
        "name":"outline"
    },
    {
        "id":4,
        "path":"/button/download",
        "name":"download"
    },
    {
        "id":5,
        "path":"/button/fade",
        "name":"fade"
    },
    {
        "id":6,
        "path":"/button/notification",
        "name":"notification"
    },
    {
        "id":7,
        "path":"/button/read-more",
        "name":"readMore"
    },
    {
        "id":8,
        "path":"/button/animated",
        "name":"animated"
    }
]