export default 
 [
    {
        id:1,
        title:"modal",
        path:"/modal"
    },
    {
        id:2,
        title:"gallery",
        path:"/gallery"
    },
    {
        id:3,
        title:"overlay",
        path:"/overlay"
    },
    {
        id:4,
        title:"thubnails",
        path:"/thubnails"
    },
    {
        id:5,
        title:"shake",
        path:"/shake"
    },
    {
        id:6,
        title:"flip",
        path:"/flip" 
    },
    {
        id:7,
        title:"slideshow",
        path:"/slideshow" 
    },
    {
        id:8,
        title:"slider",
        path:"/slider" 
    },
    {
        id:9,
        title:"validation",
        path:"/validation" 
    },
    {
        id:10,
        title:"zoom",
        path:"/zoom" 
    }
]